# if enabled players will be able to teleport through worlds (e.g. nether <-> overworld)
#
# BOOLEAN: Accepted values - [ true, false ]
#
allow-multi-world-teleport: true

# Players will need to wait set amount of time without moving to teleport
#
# INTEGER: Accepted values - [ any integer(no point values) ]
#
# WARNING: Input value in seconds.
#          0 to disable teleport delay.
#
teleport-delay: 3

# If enabled people with "PartyHomes.delay.bypass" don't need to wait for delay.
#
# BOOLEAN: Accepted values - [ true, false ]
#
enable-admin-delay-bypass: false

# if player is standing ON(not in!!!) one of this blocks he will not be able to create home here.
# list of materials: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
# could be useful to avoid trapping newly invited players, e.g. playerA invites playerB and makes his
# party home at open trap door which leads playerB to death
#
blocks-blacklist:
  - AIR
  - CAVE_AIR
  - LADDER
  - LAVA
  - WATER
  - FIRE
  # - ACACIA_FENCE_GATE
  # - OAK_TRAPDOOR

# Configure messages here.
# %> = »
# %< = «
#
messages:
  not-in-party: '&8%> &cNie jesteś w drużynie!'
  you-are-not-leader: '&8%> &cNie jesteś liderem drużyny!'
  no-home-set: '&8%> &cLider nie ustawił domu drużyny!'
  teleport-successful: '&8%> &aTeleportacja udana!'
  teleport-move: '&8%> &cTeleportacja anulowana! Poruszyłeś się!'
  teleport-in-progress: '&8%> &7Teleportacja nastąpi za &a%time%s&7.'
  sethome-successful: '&8%> &aPomyślnie ustawiono dom twojej drużyny!'
  sethome-blacklisted-block: '&8%> &cNie możesz ustawić domu na zabronionym bloku!'
  home-blacklisted-block: '&8%> &cDom twojej drużyny jest ustawiony na zabronionym bloku!'
  home-teleport-in-block: '&8%> &cDom twojej drużyny jest zablokowany. Upewnij się, że nie ma tam &ożadnych &cbloków!'
  multi-world-teleport: '&8%> &cTeleportowanie się między wymiarami jest wyłączone!'